Revert "Atest: prebuilt from aosp_cf_x86_phone-userdebug."
This reverts commit a766481a2ca7eb09b3909ca62e9ae8a31b5578bd.

Reason for revert: Due to some user's environment will get
                   ImportError: No module named protobuf,
                   roll back it first.

Change-Id: Ic72088fcfadbfa2ce2a1055cb080576d9fd6f3b9